http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: ["http://es-node-01:9200", "http://es-node-02:9200" , "http://es-node-03:9200"]
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: XbneuJCsLxBf6SSz3BKa
xpack.monitoring.enabled: false
