spring:
  datasource:
    url: jdbc:mysql://${his.cloud.datasource.ip}:33306/micro-platform?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: ${his.cloud.datasource.username}
    password: ${his.cloud.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis plus 设置
mybatis-plus:
  # 指定映射文件的位置
  mapper-locations: classpath*:com/baimicro/central/user/mapper/xml/*Mapper.xml
  # 用于搜索类型别名的包。 （包分隔符是“，; \ t \ n”）
  type-aliases-package: "com.baimicro.central.entity,com.baimicro.central.common.model"
  global-config:
    db-config:
      id-type: auto
server:
  port: 18080
