spring:
  datasource:
    url: jdbc:mysql://${his.cloud.datasource.ip}:33306/hosp_cloud?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: ${his.cloud.datasource.username}
    password: ${his.cloud.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
