# docker-compose.yml
version: '3.5'
services:
  mysql-server:
    container_name: docker-mysql
    image: mysql:5.7.22
    restart: always
    ports:
      - 33306:3306
    volumes:
      - /home/data/mysql/etc:/etc/mysql
      - /home/data/mysql/lib:/var/lib/mysql
      - /home/data/mysql/logs:/var/log/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0 --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: "baihoo!@#321"
    networks:
      - custom_net
networks:
  custom_net:
    external:
      name: overlay-net
